/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Packs */
        get: operations["packs_api_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__pid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_projects__pid__job_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/run/{stage}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Stage */
        post: operations["run_stage_api_projects__pid__run__stage__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/replan/scene/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replan One Scene */
        post: operations["replan_one_scene_api_projects__pid__replan_scene__scene_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/rewrite/scene/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rewrite One Scene
         * @description Regenerate one scene's rewrite, bypassing the cache (an explicit "try again").
         */
        post: operations["rewrite_one_scene_api_projects__pid__rewrite_scene__scene_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/screenplay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screenplay */
        get: operations["screenplay_api_projects__pid__screenplay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Comparison
         * @description Source next to adapted, per scene, with the decisions that explain the changes.
         */
        get: operations["comparison_api_projects__pid__comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/replan/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replan All Entities */
        post: operations["replan_all_entities_api_projects__pid__replan_entities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recheck */
        post: operations["recheck_api_projects__pid__recheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/characters/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Character */
        patch: operations["edit_character_api_projects__pid__characters__cid__patch"];
        trace?: never;
    };
    "/api/projects/{pid}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge */
        post: operations["merge_api_projects__pid__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/plan/{kind}/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Plan */
        patch: operations["edit_plan_api_projects__pid__plan__kind___eid__patch"];
        trace?: never;
    };
    "/api/projects/{pid}/plan/scenes/{scene_id}/keep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Keep Scene */
        post: operations["keep_scene_api_projects__pid__plan_scenes__scene_id__keep_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/decisions/{did}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Decision */
        post: operations["review_decision_api_projects__pid__decisions__did__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/warnings/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge */
        post: operations["acknowledge_api_projects__pid__warnings_acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/blockers/{what}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Blockers */
        get: operations["get_blockers_api_projects__pid__blockers__what__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/approve/{what}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_projects__pid__approve__what__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/unapprove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unapprove */
        post: operations["unapprove_api_projects__pid__unapprove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/assets/{aid}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate
         * @description A new image for the same spec. Images made from the old one become stale; only they are redone next time.
         */
        post: operations["regenerate_api_projects__pid__assets__aid__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/assets/{aid}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset File */
        get: operations["asset_file_api_projects__pid__assets__aid__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/export/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Status */
        get: operations["export_status_api_projects__pid__export_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export
         * @description Build the package. Refuses while images are missing, unless the reviewer explicitly accepts a partial pack.
         */
        post: operations["export_api_projects__pid__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/export/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Download */
        get: operations["export_download_api_projects__pid__export_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AckBody */
        AckBody: {
            /** Warning Id */
            warning_id: string;
            /**
             * Acknowledged
             * @default true
             */
            acknowledged: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * AdaptationDecision
         * @description One explained cultural choice. The plan is a list of these.
         */
        AdaptationDecision: {
            /** Id */
            id: string;
            dimension: components["schemas"]["Dimension"];
            /** Source Scene Ids */
            source_scene_ids?: string[];
            /** Entity Id */
            entity_id?: string | null;
            /** Original */
            original: string;
            /** Adapted */
            adapted: string;
            /** Reason */
            reason: string;
            /**
             * Basis
             * @default judgment
             * @enum {string}
             */
            basis: "pack" | "judgment";
            /** Fact Ids */
            fact_ids?: string[];
            /**
             * Uncertain
             * @default false
             */
            uncertain: boolean;
            /**
             * Uncertain Reason
             * @default
             */
            uncertain_reason: string;
            /** @default proposed */
            status: components["schemas"]["ReviewStatus"];
            /**
             * Reviewer Note
             * @default
             */
            reviewer_note: string;
        };
        /**
         * AdaptationPlan
         * @description What the project stores. `problems` and `failed_scenes` are shown on the review screen.
         */
        AdaptationPlan: {
            /**
             * Model
             * @default
             */
            model: string;
            entities?: components["schemas"]["EntityPlan"] | null;
            /** Scenes */
            scenes?: {
                [key: string]: components["schemas"]["ScenePlan"];
            };
            /** Failed Scenes */
            failed_scenes?: {
                [key: string]: string;
            };
            /** Problems */
            problems?: string[];
            /** Stale Scenes */
            stale_scenes?: string[];
        };
        /** AdaptedLine */
        AdaptedLine: {
            /** Source Scene Id */
            source_scene_id: string;
            /** Decision Ids */
            decision_ids?: string[];
            /** Character Id */
            character_id?: string | null;
            /** @default dialogue */
            kind: components["schemas"]["LineKind"];
            /** Text */
            text: string;
            /**
             * Gloss
             * @default
             */
            gloss: string;
            /** Source Line */
            source_line?: number | null;
            /** Event Ids */
            event_ids?: number[];
            /**
             * Uncertain
             * @default false
             */
            uncertain: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** AdaptedScene */
        AdaptedScene: {
            /** Source Scene Id */
            source_scene_id: string;
            /**
             * Heading
             * @default
             */
            heading: string;
            /** Lines */
            lines?: components["schemas"]["AdaptedLine"][];
            /** Problems */
            problems?: string[];
        };
        /** AffectedScenes */
        AffectedScenes: {
            /** Affected Scenes */
            affected_scenes: string[];
        };
        /** Approval */
        Approval: {
            /**
             * Characters
             * @default false
             */
            characters: boolean;
            /**
             * Plan
             * @default false
             */
            plan: boolean;
            /**
             * Costumes
             * @default false
             */
            costumes: boolean;
        };
        /** ApprovalResult */
        ApprovalResult: {
            /** Approved */
            approved: boolean;
            /**
             * Status
             * @default
             */
            status: string;
            /**
             * Waiting For
             * @default []
             */
            waiting_for: string[];
            /** Blocked By */
            blocked_by?: string | null;
        };
        /** Asset */
        Asset: {
            /** Id */
            id: string;
            kind: components["schemas"]["AssetKind"];
            /** Entity Id */
            entity_id: string;
            /** @default pending */
            status: components["schemas"]["AssetStatus"];
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Prompt
             * @default
             */
            prompt: string;
            /** Spec */
            spec?: {
                [key: string]: unknown;
            };
            /**
             * Spec Hash
             * @default
             */
            spec_hash: string;
            /** Reference Asset Ids */
            reference_asset_ids?: string[];
            /**
             * Path
             * @default
             */
            path: string;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /**
             * Error
             * @default
             */
            error: string;
            /** Problems */
            problems?: string[];
            /**
             * Seconds
             * @default 0
             */
            seconds: number;
            /**
             * Size
             * @default
             */
            size: string;
        };
        /**
         * AssetKind
         * @enum {string}
         */
        AssetKind: "character_ref" | "costume_sheet" | "scene_keyframe";
        /**
         * AssetStatus
         * @enum {string}
         */
        AssetStatus: "pending" | "generated" | "failed" | "stale";
        /** Blockers */
        Blockers: {
            /** What */
            what: string;
            /** Blockers */
            blockers: string[];
        };
        /** Body_create_project_api_projects_post */
        Body_create_project_api_projects_post: {
            /** Pack Id */
            pack_id: string;
            /** Region */
            region: string;
            /** Setting */
            setting: string;
            /** Output Script */
            output_script: string;
            /** Text */
            text?: string | null;
            /** File */
            file?: string | null;
        };
        /** Character */
        Character: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /** Age */
            age?: number | null;
            /**
             * Role
             * @default
             */
            role: string;
            /** Relationships */
            relationships?: components["schemas"]["Relationship"][];
            /** Relationship Notes */
            relationship_notes?: string[];
            /**
             * Personality
             * @default
             */
            personality: string;
            /**
             * Dialect
             * @default
             */
            dialect: string;
            /**
             * Emotional State
             * @default
             */
            emotional_state: string;
            /**
             * Physical Description
             * @default
             */
            physical_description: string;
            /**
             * Adapted Name
             * @default
             */
            adapted_name: string;
            /**
             * Adapted Name Native
             * @default
             */
            adapted_name_native: string;
            /**
             * Role Adapted
             * @default
             */
            role_adapted: string;
            /**
             * Speech Register
             * @default
             */
            speech_register: string;
            /** Address Terms */
            address_terms?: string[];
            /**
             * Grooming
             * @default
             */
            grooming: string;
            /** Scene Ids */
            scene_ids?: string[];
            /**
             * Approved
             * @default false
             */
            approved: boolean;
        };
        /** CharacterPlan */
        CharacterPlan: {
            /** Character Id */
            character_id: string;
            /** Name Roman */
            name_roman: string;
            /** Name Native */
            name_native: string;
            /**
             * Role Adapted
             * @default
             */
            role_adapted: string;
            /**
             * Speech Register
             * @default
             */
            speech_register: string;
            /**
             * Appearance
             * @default
             */
            appearance: string;
            /**
             * Grooming
             * @default
             */
            grooming: string;
            /** Address Terms */
            address_terms?: string[];
        };
        /**
         * CharacterState
         * @description Derived (never hand-edited): a character's state at the END of a scene.
         */
        CharacterState: {
            /**
             * Costume Id
             * @default
             */
            costume_id: string;
            /** Carrying */
            carrying?: string[];
            /** Injuries */
            injuries?: string[];
            /** Knows */
            knows?: string[];
        };
        /** ComparisonScene */
        ComparisonScene: {
            /** Scene Id */
            scene_id: string;
            /** Source Text */
            source_text: string;
            adapted?: components["schemas"]["AdaptedScene"] | null;
            /** Decisions */
            decisions: components["schemas"]["AdaptationDecision"][];
            /**
             * Failed
             * @default
             */
            failed: string;
        };
        /** ContinuityWarning */
        ContinuityWarning: {
            /**
             * Id
             * @default
             */
            id: string;
            /** Code */
            code: string;
            /** @default warning */
            severity: components["schemas"]["Severity"];
            /** Message */
            message: string;
            /** Entity Id */
            entity_id?: string | null;
            /** Affected Scene Ids */
            affected_scene_ids?: string[];
            /**
             * Acknowledged
             * @default false
             */
            acknowledged: boolean;
            /**
             * Ack Note
             * @default
             */
            ack_note: string;
        };
        /** Costume */
        Costume: {
            /** Id */
            id: string;
            /** Character Id */
            character_id: string;
            /** Source Garments */
            source_garments?: string | null;
            /**
             * Garments
             * @default
             */
            garments: string;
            /**
             * Fabrics
             * @default
             */
            fabrics: string;
            /**
             * Colours
             * @default
             */
            colours: string;
            /**
             * Footwear
             * @default
             */
            footwear: string;
            /**
             * Jewellery
             * @default
             */
            jewellery: string;
            /**
             * Headwear
             * @default
             */
            headwear: string;
            /**
             * Grooming
             * @default
             */
            grooming: string;
            /** Scene Ids */
            scene_ids?: string[];
            /**
             * Change Reason
             * @default
             */
            change_reason: string;
            /**
             * Approved
             * @default false
             */
            approved: boolean;
        };
        /** CostumePlan */
        CostumePlan: {
            /** Costume Id */
            costume_id: string;
            /** Garments */
            garments: string;
            /**
             * Fabrics
             * @default
             */
            fabrics: string;
            /**
             * Colours
             * @default
             */
            colours: string;
            /**
             * Footwear
             * @default
             */
            footwear: string;
            /**
             * Jewellery
             * @default
             */
            jewellery: string;
            /**
             * Headwear
             * @default
             */
            headwear: string;
            /**
             * Grooming
             * @default
             */
            grooming: string;
            /**
             * Change Reason
             * @default
             */
            change_reason: string;
        };
        /** Created */
        Created: {
            /** Id */
            id: string;
            /** Scenes */
            scenes: number;
            /** Problems */
            problems: string[];
        };
        /**
         * CultureSelection
         * @description What the user picked. Every field is required: no baked-in defaults.
         */
        CultureSelection: {
            /** Pack Id */
            pack_id: string;
            /** Region */
            region: string;
            setting: components["schemas"]["Setting"];
            /** Output Script */
            output_script: string;
        };
        /**
         * DecisionDraft
         * @description One explained cultural choice, exactly as the model wrote it.
         */
        DecisionDraft: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "verbal" | "non_verbal" | "character" | "visual_world" | "story_world";
            /**
             * Entity Id
             * @default
             */
            entity_id: string;
            /** Original */
            original: string;
            /** Adapted */
            adapted: string;
            /** Reason */
            reason: string;
            /**
             * Basis
             * @enum {string}
             */
            basis: "pack" | "judgment";
            /** Fact Ids */
            fact_ids?: string[];
            /**
             * Uncertain
             * @default false
             */
            uncertain: boolean;
        };
        /**
         * Dimension
         * @description What an adaptation decision is about (mirrors the brief's table).
         * @enum {string}
         */
        Dimension: "verbal" | "non_verbal" | "character" | "visual_world" | "story_world";
        /** EntityPlan */
        EntityPlan: {
            /**
             * Season And Period
             * @default
             */
            season_and_period: string;
            /** Characters */
            characters?: components["schemas"]["CharacterPlan"][];
            /** Costumes */
            costumes?: components["schemas"]["CostumePlan"][];
            /** Locations */
            locations?: components["schemas"]["LocationPlan"][];
            /** Props */
            props?: components["schemas"]["PropPlan"][];
            /** Decisions */
            decisions?: components["schemas"]["DecisionDraft"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntExt
         * @enum {string}
         */
        IntExt: "INT" | "EXT" | "INT/EXT";
        /** JobInfo */
        JobInfo: {
            /** Name */
            name: string;
            /** State */
            state: string;
            /**
             * Error
             * @default
             */
            error: string;
            /** Started */
            started?: number | null;
            /** Finished */
            finished?: number | null;
            /**
             * Progress
             * @default
             */
            progress: string;
            /** Done */
            done?: number | null;
            /** Total */
            total?: number | null;
        };
        /**
         * LineKind
         * @enum {string}
         */
        LineKind: "dialogue" | "action" | "gesture" | "sound";
        /** Location */
        Location: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Adapted Name
             * @default
             */
            adapted_name: string;
            /**
             * Adapted Name Native
             * @default
             */
            adapted_name_native: string;
            /** Sub Locations */
            sub_locations?: string[];
            /**
             * Description
             * @default
             */
            description: string;
            /** Scene Ids */
            scene_ids?: string[];
        };
        /** LocationPlan */
        LocationPlan: {
            /** Location Id */
            location_id: string;
            /**
             * Name Roman
             * @default
             */
            name_roman: string;
            /**
             * Name Native
             * @default
             */
            name_native: string;
            /** Description */
            description: string;
        };
        /** MentionedCharacter */
        MentionedCharacter: {
            /** Name */
            name: string;
            /** Other Names */
            other_names?: string[];
            /**
             * Age
             * @default
             */
            age: string;
            /**
             * Role
             * @default
             */
            role: string;
            /** Relationships */
            relationships?: string[];
            /**
             * Personality
             * @default
             */
            personality: string;
            /**
             * Costume
             * @default
             */
            costume: string;
            /**
             * Emotional State
             * @default
             */
            emotional_state: string;
            /**
             * Enters
             * @default false
             */
            enters: boolean;
            /**
             * Exits
             * @default false
             */
            exits: boolean;
        };
        /** MentionedProp */
        MentionedProp: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Holder At Start
             * @default
             */
            holder_at_start: string;
            /**
             * Holder At End
             * @default
             */
            holder_at_end: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** MergeBody */
        MergeBody: {
            /** Kind */
            kind: string;
            /** Keep Id */
            keep_id: string;
            /** Drop Id */
            drop_id: string;
        };
        /**
         * ProductionElements
         * @description Everything the art/sound departments need for a scene.
         */
        ProductionElements: {
            /** Set Dressing */
            set_dressing?: string[];
            /** Food */
            food?: string[];
            /** Vehicles */
            vehicles?: string[];
            /** Animals */
            animals?: string[];
            /** Extras */
            extras?: string[];
            /** Rituals */
            rituals?: string[];
            /** Gestures */
            gestures?: string[];
            /** Sound Music */
            sound_music?: string[];
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "created" | "extracted" | "normalized" | "plan_ready" | "approved" | "rewritten" | "generated" | "exported";
        /** ProjectSummary */
        ProjectSummary: {
            /** Id */
            id: string;
            /** Source Filename */
            source_filename: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            /** Culture */
            culture: string;
            /** Region */
            region: string;
            /** Scenes */
            scenes: number;
            /** Characters */
            characters: number;
            /** Decisions */
            decisions: number;
            /** Flagged Decisions */
            flagged_decisions: number;
            job?: components["schemas"]["JobInfo"] | null;
        };
        /**
         * ProjectView
         * @description The whole project plus what the UI needs to render it.
         */
        ProjectView: {
            /** Id */
            id?: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** @default created */
            status: components["schemas"]["ProjectStatus"];
            /**
             * Source Filename
             * @default
             */
            source_filename: string;
            /**
             * Source Text
             * @default
             */
            source_text: string;
            /** Extraction Problems */
            extraction_problems?: string[];
            /** Source Scenes */
            source_scenes?: components["schemas"]["SourceScene"][];
            selection?: components["schemas"]["CultureSelection"] | null;
            /** Scenes */
            scenes?: components["schemas"]["Scene"][];
            /** Characters */
            characters?: components["schemas"]["Character"][];
            /** Locations */
            locations?: components["schemas"]["Location"][];
            /** Props */
            props?: components["schemas"]["Prop"][];
            /** Costumes */
            costumes?: components["schemas"]["Costume"][];
            /** User Edits */
            user_edits?: string[];
            /** Normalization Log */
            normalization_log?: string[];
            /** Warnings */
            warnings?: components["schemas"]["ContinuityWarning"][];
            /**
             * Continuity Checked
             * @default false
             */
            continuity_checked: boolean;
            plan?: components["schemas"]["AdaptationPlan"] | null;
            /** Decisions */
            decisions?: components["schemas"]["AdaptationDecision"][];
            /** Adapted Scenes */
            adapted_scenes?: components["schemas"]["AdaptedScene"][];
            /** Rewrite Failed */
            rewrite_failed?: {
                [key: string]: string;
            };
            /** Assets */
            assets?: components["schemas"]["Asset"][];
            approval?: components["schemas"]["Approval"];
            job?: components["schemas"]["JobInfo"] | null;
            /**
             * Blocking Warning Ids
             * @default []
             */
            blocking_warning_ids: string[];
            /**
             * Review Problems
             * @default []
             */
            review_problems: string[];
        };
        /** Prop */
        Prop: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Adapted Name
             * @default
             */
            adapted_name: string;
            /**
             * Adapted Name Native
             * @default
             */
            adapted_name_native: string;
            /** Aliases */
            aliases?: string[];
            /**
             * Description
             * @default
             */
            description: string;
            /** Scene Ids */
            scene_ids?: string[];
        };
        /** PropPlan */
        PropPlan: {
            /** Prop Id */
            prop_id: string;
            /** Name Roman */
            name_roman: string;
            /** Name Native */
            name_native: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** Relationship */
        Relationship: {
            /** Other Id */
            other_id: string;
            /** Relation */
            relation: string;
        };
        /** ReviewBody */
        ReviewBody: {
            /** Status */
            status: string;
            /** Adapted */
            adapted?: string | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "proposed" | "accepted" | "edited" | "rejected";
        /** Scene */
        Scene: {
            /** Scene Id */
            scene_id: string;
            /** Number */
            number: number;
            /** @default INT */
            int_ext: components["schemas"]["IntExt"];
            /**
             * Location Id
             * @default
             */
            location_id: string;
            /**
             * Sub Location
             * @default
             */
            sub_location: string;
            /**
             * Time
             * @default
             */
            time: string;
            /**
             * Day
             * @default
             */
            day: string;
            /**
             * Weather
             * @default
             */
            weather: string;
            /**
             * Mood
             * @default
             */
            mood: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Dramatic Purpose
             * @default
             */
            dramatic_purpose: string;
            /**
             * Source Text
             * @default
             */
            source_text: string;
            /** Characters */
            characters?: string[];
            /** Entrances */
            entrances?: string[];
            /** Exits */
            exits?: string[];
            /** Costumes */
            costumes?: {
                [key: string]: string;
            };
            /** Props In */
            props_in?: string[];
            /** Props Out */
            props_out?: string[];
            /** Prop Holder Start */
            prop_holder_start?: {
                [key: string]: string;
            };
            /** Prop Holder End */
            prop_holder_end?: {
                [key: string]: string;
            };
            /** State Changes */
            state_changes?: components["schemas"]["StateChange"][];
            production?: components["schemas"]["ProductionElements"];
            /**
             * Emotional Change
             * @default
             */
            emotional_change: string;
            /** Continuity Warnings */
            continuity_warnings?: string[];
            /** States */
            states?: {
                [key: string]: components["schemas"]["CharacterState"];
            };
        };
        /** SceneExtraction */
        SceneExtraction: {
            /** Scene Number */
            scene_number: number;
            /**
             * Int Ext
             * @default
             */
            int_ext: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Sub Location
             * @default
             */
            sub_location: string;
            /**
             * Time
             * @default
             */
            time: string;
            /**
             * Day
             * @default
             */
            day: string;
            /**
             * Weather
             * @default
             */
            weather: string;
            /**
             * Mood
             * @default
             */
            mood: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Dramatic Purpose
             * @default
             */
            dramatic_purpose: string;
            /**
             * Emotional Change
             * @default
             */
            emotional_change: string;
            /** Characters */
            characters?: components["schemas"]["MentionedCharacter"][];
            /** Props */
            props?: components["schemas"]["MentionedProp"][];
            /** Events */
            events?: components["schemas"]["StateEvent"][];
            /** Set Dressing */
            set_dressing?: string[];
            /** Food */
            food?: string[];
            /** Vehicles */
            vehicles?: string[];
            /** Animals */
            animals?: string[];
            /** Extras */
            extras?: string[];
            /** Rituals */
            rituals?: string[];
            /** Gestures */
            gestures?: string[];
            /** Sound Music */
            sound_music?: string[];
        };
        /** ScenePlan */
        ScenePlan: {
            /** Scene Id */
            scene_id: string;
            /**
             * Setting Notes
             * @default
             */
            setting_notes: string;
            /**
             * Dialogue Notes
             * @default
             */
            dialogue_notes: string;
            /** Gestures */
            gestures?: string[];
            /** Food */
            food?: string[];
            /** Sound Music */
            sound_music?: string[];
            /** Rituals */
            rituals?: string[];
            /** Decisions */
            decisions?: components["schemas"]["DecisionDraft"][];
        };
        /**
         * Setting
         * @enum {string}
         */
        Setting: "rural" | "urban";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "warning" | "error";
        /**
         * SourceScene
         * @description One scene of the source screenplay plus what was extracted from it.
         */
        SourceScene: {
            /** Number */
            number: number;
            /**
             * Heading
             * @default
             */
            heading: string;
            /** Text */
            text: string;
            extraction?: components["schemas"]["SceneExtraction"] | null;
            /**
             * Error
             * @default
             */
            error: string;
            /** Problems */
            problems?: string[];
        };
        /**
         * StateChange
         * @description Something that changes for a character or prop during a scene.
         */
        StateChange: {
            kind: components["schemas"]["StateChangeKind"];
            /** Character Id */
            character_id: string;
            /**
             * Item
             * @default
             */
            item: string;
            /** To Character Id */
            to_character_id?: string | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * StateChangeKind
         * @enum {string}
         */
        StateChangeKind: "prop_gain" | "prop_loss" | "prop_transfer" | "injury_gain" | "injury_heal" | "knowledge_gain" | "costume_change" | "relationship_change";
        /** StateEvent */
        StateEvent: {
            /** Kind */
            kind: string;
            /** Character */
            character: string;
            /**
             * Item
             * @default
             */
            item: string;
            /**
             * To Character
             * @default
             */
            to_character: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** UnapproveBody */
        UnapproveBody: {
            /** What */
            what?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    packs_api_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_project_api_projects_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Created"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__pid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_projects__pid__job_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"] | {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stage_api_projects__pid__run__stage__post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                pid: string;
                stage: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replan_one_scene_api_projects__pid__replan_scene__scene_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rewrite_one_scene_api_projects__pid__rewrite_scene__scene_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screenplay_api_projects__pid__screenplay_get: {
        parameters: {
            query?: {
                gloss?: boolean;
            };
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comparison_api_projects__pid__comparison_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonScene"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replan_all_entities_api_projects__pid__replan_entities_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recheck_api_projects__pid__recheck_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_character_api_projects__pid__characters__cid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AffectedScenes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_api_projects__pid__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AffectedScenes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_plan_api_projects__pid__plan__kind___eid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                kind: string;
                eid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AffectedScenes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    keep_scene_api_projects__pid__plan_scenes__scene_id__keep_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_decision_api_projects__pid__decisions__did__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                did: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdaptationDecision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_api_projects__pid__warnings_acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AckBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blockers_api_projects__pid__blockers__what__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                what: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blockers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_projects__pid__approve__what__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                what: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unapprove_api_projects__pid__unapprove_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UnapproveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_api_projects__pid__assets__aid__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                aid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_file_api_projects__pid__assets__aid__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                aid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_status_api_projects__pid__export_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_projects__pid__export_post: {
        parameters: {
            query?: {
                allow_partial?: boolean;
            };
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_download_api_projects__pid__export_download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
